# Generated by Django 2.1.7 on 2019-04-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('deadline', models.DateTimeField(verbose_name='报名截止时间')),
                ('city', models.CharField(max_length=64, verbose_name='城市')),
                ('address', models.CharField(max_length=64, verbose_name='地址')),
                ('cover', models.CharField(max_length=100, verbose_name='图片')),
                ('desc', models.TextField(verbose_name='介绍')),
                ('detail', models.TextField(verbose_name='详情')),
                ('sponsor', models.CharField(max_length=64, verbose_name='主办市')),
                ('url', models.CharField(max_length=100, verbose_name='链接')),
                ('status', models.SmallIntegerField(verbose_name='状态')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'tb_activity',
            },
        ),
    ]
