# Generated by Django 2.1.7 on 2019-04-01 17:02

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='语言标签')),
                ('like_counts', models.IntegerField(default=0, verbose_name='关注数')),
                ('content', models.CharField(blank=True, max_length=512, null=True, verbose_name='语言标签简介')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='discuss.LabelCategory', verbose_name='所属父级语言标签')),
                ('user_like', models.ManyToManyField(db_table='tb_user_like_label', to=settings.AUTH_USER_MODEL, verbose_name='用户关注')),
            ],
            options={
                'verbose_name': '语言标签分类',
                'verbose_name_plural': '语言标签分类',
                'db_table': 'tb_label_category',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='问题详细信息')),
                ('clicks', models.IntegerField(default=0, verbose_name='浏览量')),
                ('answer_counts', models.IntegerField(default=0, verbose_name='评论量')),
                ('like_counts', models.IntegerField(default=0, verbose_name='问题点赞量')),
                ('label', models.ManyToManyField(db_table='tb_label_question', to='discuss.LabelCategory', verbose_name='问题所属标签')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='问题发布的用户')),
                ('user_like', models.ManyToManyField(db_table='tb_user_like_question', related_name='like_questions', to=settings.AUTH_USER_MODEL, verbose_name='问题点赞的用户')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
                'db_table': 'tb_question',
            },
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment_content', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='评论详细信息')),
                ('like_counts', models.IntegerField(default=0, verbose_name='点赞数')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='discuss.QuestionComment', verbose_name='所属父级评论')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discuss.Question', verbose_name='评论所属问题')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='评论发布的用户')),
                ('user_like', models.ManyToManyField(db_table='tb_user_like_comment', related_name='like_comment', to=settings.AUTH_USER_MODEL, verbose_name='评论点赞的用户')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'db_table': 'tb_question_comment',
            },
        ),
    ]
